# Generated by Django 5.0.4 on 2024-05-17 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shippinaddres'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinaddres',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order'),
        ),
    ]
